### ISSUE TITLE
PGP, Tor, and You - Add presentation slides/docs

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/Talks#15]
@Ricky54326 
- PGP, Tor, and You | [Riccardo Mutschlechner](https://github.com/ricky54326)
  - UPCOMING 4/13

**Comment by WowSuchRicky** [comment]
I've been so lazy with this, after my midterm tomorrow it's definitely going to get done.

**Comment by MikeCook9994** [comment]
Did it get done?

**Comment by katamaritaco** [comment]
:camel:

**Comment by WowSuchRicky** [comment]
Sorry, I've been kill the last month. After I recover from this surgery, I'll do it right away and throw it up.

**Comment by spwilson2** [comment]
:camel:

**Comment by LOZORD** [comment]
🐫

**Comment by WowSuchRicky** [comment]
Sorry My last update didn't come through. Going to give this talk this coming year sometime instead of recording after getting some feedback on it. Hope that's cool. Let's close this for now.

On Jul 27, 2016, at 4:06 PM, Leo Rudberg <notifications@github.com<mailto:notifications@github.com>> wrote:

?

##
